  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
    ports:
      - "5433:5432" # Пробрасываем на 5433, чтобы не конфликтовать с локальным Postgres если он есть
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d project_db"]
      interval: 5s
      timeout: 5s
      retries: 5
# Backend (FastAPI)
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000" # Пробрасываем порт, чтобы фронтенд мог слать запросы на localhost:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env # Подключаем ваш .env файл с настройками почты
    environment:
      # Переопределяем настройки БД для работы внутри Docker сети
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
      # Redis (если нужен)
      REDIS_HOST: redis

  # Frontend (React + Nginx)
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:80" # Открываем сайт на localhost:5173
    depends_on:
      - backend

  volumes:
    postgres_data:
